language: perl
perl:
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
before_install:
  - "cpanm --notest Linux::Inotify2"
  - "cpanm --notest Regexp::Assemble"
  - "dzil authordeps | xargs cpanm"
install: "dzil listdeps | xargs cpanm"
script: "dzil test"
